create table room (capacity integer not null, id bigint generated by default as identity, amenities varchar(255), name varchar(255), primary key (id));
create table room_price (price integer not null, id bigint generated by default as identity, room_id bigint not null, type varchar(255) check (type in ('STANDARD','GOLD','PLATINUM')), primary key (id));
alter table if exists room_price add constraint FKfj3ode2586k91fceuwrtfxhqp foreign key (room_id) references room;
