server:
  port: 8083

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false
#resilience4j.circuitbreaker.metrics.use_legacy_binder: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      failureRateThreshold: 30
      eventConsumerBufferSize: 10
  instances:
    rooms:
      baseConfig: default
    singleRoom:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
  instances:
    rooms:
      baseConfig: default
    singleRoom:
      baseConfig: default
      ignoreExceptions:
        - org.springframework.web.server.ResponseStatusException

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms
  instances:
    rooms:
      baseConfig: default
    singleRoom:
      baseConfig: default

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      writableStackTraceEnabled: true
  instances:
    rooms:
      baseConfig: default
    singleRoom:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
  instances:
    rooms:
      baseConfig: default
    singleRoom:
      baseConfig: default
# resilience4j.timelimiter:
#   configs:
#     default:
#       timeoutDuration: 2s
#       cancelRunningFuture: true
#   instances:
#     rooms:
#       baseConfig: default
#     singleRoom:
#       baseConfig: default
